# Generated by Django 5.1.3 on 2024-11-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_post_image_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('orange', 'Orange'), ('white', 'White'), ('beige', 'Beige'), ('black', 'Black'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='material',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('metal', 'Metal'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='shape',
            field=models.CharField(choices=[('cylinder', 'Cylinder'), ('square', 'Square'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='weight',
            field=models.CharField(choices=[('0-2.5kg', '0-2.5kg'), ('2.5-5kg', '2.5-5kg'), ('5-10kg', '5-10kg'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
