# Generated by Django 5.1.3 on 2024-11-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_post_color_post_material_post_shape_post_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hardness',
            field=models.CharField(choices=[('soft', 'Soft'), ('medium', 'Medium'), ('hard', 'Hard'), ('rigid', 'Rigid'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('europe', 'Europe'), ('asia', 'Asia'), ('north america', 'North America'), ('south america', 'South America'), ('africa', 'Africa'), ('australia', 'Australia'), ('antarctica', 'Antarctica'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='smell',
            field=models.CharField(choices=[('woody', 'Woody'), ('fragrant', 'Fragrant'), ('fruity', 'Fruity'), ('minty', 'Minty'), ('sweet', 'Sweet'), ('popcorn', 'Popcorn'), ('lemon', 'Lemon'), ('chemical', 'Chemical'), ('pungent', 'Pungent'), ('decayed', 'Decayed'), ('none', 'None'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='taste',
            field=models.CharField(choices=[('sweet', 'Sweet'), ('sour', 'Sour'), ('bitter', 'Bitter'), ('salty', 'Salty'), ('umami', 'Umami'), ('savory', 'Savory'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='texture',
            field=models.CharField(choices=[('smooth', 'Smooth'), ('rough', 'Rough'), ('grainy', 'Grainy'), ('slimy', 'Slimy'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='time_period',
            field=models.CharField(choices=[('stone age', 'Stone Age'), ('iron age', 'Iron Age'), ('classical era', 'Classical Era'), ('medieval era', 'Medieval Era'), ('early modern era', 'Early Modern Era'), ('modern era', 'Modern Era'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='value',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('luxury', 'Luxury'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
