# Generated by Django 5.1.3 on 2024-12-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tag_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple'), ('red-orange', 'Red-Orange'), ('yellow-orange', 'Yellow-Orange'), ('yellow-green', 'Yellow-Green'), ('blue-green', 'Blue-Green'), ('blue-purple', 'Blue-Purple'), ('red-purple', 'Red-Purple'), ('black', 'Black'), ('white', 'White'), ('beige', 'Beige'), ('gray', 'Gray'), ('brown', 'Brown'), ('pink', 'Pink'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('beige', 'Beige'), ('teal', 'Teal'), ('lavender', 'Lavender'), ('maroon', 'Maroon'), ('navy', 'Navy'), ('olive', 'Olive'), ('gold', 'Gold'), ('silver', 'Silver'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='hardness',
            field=models.CharField(choices=[('soft', 'Soft'), ('medium-soft', 'Medium-Soft'), ('medium', 'Medium'), ('medium-hard', 'Medium-Hard'), ('hard', 'Hard'), ('very-hard', 'Very-Hard'), ('rigid', 'Rigid'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='material',
            field=models.CharField(choices=[('wood', 'Wood'), ('metal', 'Metal'), ('plastic', 'Plastic'), ('glass', 'Glass'), ('stone', 'Stone'), ('ceramic', 'Ceramic'), ('fabric', 'Fabric'), ('leather', 'Leather'), ('rubber', 'Rubber'), ('paper', 'Paper'), ('cardboard', 'Cardboard'), ('concrete', 'Concrete'), ('brick', 'Brick'), ('foam', 'Foam'), ('carbon-fiber', 'Carbon-Fiber'), ('kevlar', 'Kevlar'), ('silicone', 'Silicone'), ('clay', 'Clay'), ('wax', 'Wax'), ('gold', 'Gold'), ('silver', 'Silver'), ('copper', 'Copper'), ('aluminum', 'Aluminum'), ('iron', 'Iron'), ('steel', 'Steel'), ('bronze', 'Bronze'), ('brass', 'Brass'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='shape',
            field=models.CharField(choices=[('circle', 'Circle'), ('square', 'Square'), ('rectangle', 'Rectangle'), ('triangle', 'Triangle'), ('oval', 'Oval'), ('pentagon', 'Pentagon'), ('hexagon', 'Hexagon'), ('heptagon', 'Heptagon'), ('octagon', 'Octagon'), ('nonagon', 'Nonagon'), ('decagon', 'Decagon'), ('cube', 'Cube'), ('cuboid', 'Cuboid'), ('sphere', 'Sphere'), ('cylinder', 'Cylinder'), ('cone', 'Cone'), ('pyramid', 'Pyramid'), ('prism', 'Prism'), ('torus', 'Torus'), ('star', 'Star'), ('heart', 'Heart'), ('diamond', 'Diamond'), ('parallelogram', 'Parallelogram'), ('trapezoid', 'Trapezoid'), ('rhombus', 'Rhombus'), ('crescent', 'Crescent'), ('arrow', 'Arrow'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='texture',
            field=models.CharField(choices=[('smooth', 'Smooth'), ('rough', 'Rough'), ('grainy', 'Grainy'), ('slimy', 'Slimy'), ('slippery', 'Slippery'), ('matte', 'Matte'), ('glossy', 'Glossy'), ('bumpy', 'Bumpy'), ('gritty', 'Gritty'), ('velvety', 'Velvety'), ('fuzzy', 'Fuzzy'), ('silky', 'Silky'), ('coarse', 'Coarse'), ('pebbled', 'Pebbled'), ('polished', 'Polished'), ('woven', 'Woven'), ('hairy', 'Hairy'), ('sticky', 'Sticky'), ('spongy', 'Spongy'), ('crispy', 'Crispy'), ('wrinkled', 'Wrinkled'), ('slick', 'Slick'), ('pitted', 'Pitted'), ('corrugated', 'Corrugated'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_period',
            field=models.CharField(choices=[('medieval era', 'Medieval Era'), ('early modern era', 'Early Modern Era'), ('prehistoric', 'Prehistoric'), ('stone age', 'Stone Age'), ('bronze-age', 'Bronze Age'), ('iron age', 'Iron Age'), ('classical era', 'Classical Era'), ('middle-ages', 'Middle Ages'), ('renaissance', 'Renaissance'), ('age-of-exploration', 'Age of Exploration'), ('industrial-age', 'Industrial Age'), ('modern era', 'Modern Era'), ('information-age', 'Information Age'), ('paleozoic-era', 'Paleozoic Era'), ('mesozoic-era', 'Mesozoic Era'), ('cenozoic-era', 'Cenozoic Era'), ('jurassic-period', 'Jurassic Period'), ('cretaceous-period', 'Cretaceous Period'), ('pleistocene-epoch', 'Pleistocene Epoch'), ('holocene-epoch', 'Holocene Epoch'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='value',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('luxury', 'Luxury'), ('fragile', 'Fragile'), ('durable', 'Durable'), ('lightweight', 'Lightweight'), ('heavy', 'Heavy'), ('expensive', 'Expensive'), ('affordable', 'Affordable'), ('luxurious', 'Luxurious'), ('eco-friendly', 'Eco-Friendly'), ('recyclable', 'Recyclable'), ('disposable', 'Disposable'), ('handcrafted', 'Handcrafted'), ('mass-produced', 'Mass-Produced'), ('versatile', 'Versatile'), ('customizable', 'Customizable'), ('limited-edition', 'Limited Edition'), ('unique', 'Unique'), ('high-quality', 'High-Quality'), ('low-quality', 'Low-Quality'), ('rare', 'Rare'), ('common', 'Common'), ('portable', 'Portable'), ('compact', 'Compact'), ('ergonomic', 'Ergonomic'), ('innovative', 'Innovative'), ('traditional', 'Traditional'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
