# Generated by Django 5.1.3 on 2024-12-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_post_color_alter_post_hardness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='depth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='size_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('inch', 'Inches')], default='cm', max_length=10),
        ),
    ]
